baseURL = 'https://blog.turingzy.cn/'
languageCode = 'en-us'
title = 'TuringNest'
theme = 'yinyang'
DefaultContentLanguage = "cn"

[params]
headTitle = "Yang Zhang"
mainSections = ["posts"]


[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[[params.socials]]
name = "About Me"
link = "https://joway.io"
[[params.socials]]
name = "Github"
link = "https://github.com/joway"