baseURL = 'https://blog.turingzy.cn'
languageCode = 'en-us'
title = 'TuringNest'
theme = 'yinyang'

[permalinks]
  posts = "/posts/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true #使用行内样式
    style = "github"
    tabWidth = 2
[outputs]
  home = ["html","rss"]
  section = ["html"]
  taxonomy = ["html"]
  term = ["html"]

[params]
  mainSections = ["posts"]
  headTitle = "Yang Zhang"
  description = "「I came, I saw, I conquered」"
  lazyImage = true
  siteStartDate = "2025-06-01"
  # google tag.js
  extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=G-66JHC5XMXL"></script>'
  # gisus
  giscus = true
  giscus_repo = "turingzy-dev/blog-giscus"
  giscus_repo_id = "R_kgDOPTLcow"
  giscus_category = "Announcements"
  giscus_category_id = "DIC_kwDOPTLco84Ctb-O"
[params.author]
  name = "Zhang Yang"
  email = 'email@turingzy.cn'
  homepage = "/about/"
[[params.socials]]
  name = "Projects"
  link = "/projects/"
[[params.socials]]
  name = "About"
  link = "/about/"
  [[params.socials]]
  name = "RSS"
  link = "https://blog.turingzy.cn/index.xml"