baseURL = 'https://blog.turingzy.cn/'
languageCode = 'en-us'
title = 'TuringNest'
theme = 'yinyang'
DefaultContentLanguage = "cn"


[languages]
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[params]
headTitle = "Yang Zhang"
description = "「I came, I saw, I conquered」"
mainSections = ["posts"]
# google tag.js
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=G-66JHC5XMXL"></script>'
# gisus
giscus = true
giscus_repo = "turingzy-dev/blog-giscus"
giscus_repo_id = "R_kgDOPTLcow"
giscus_category = "Announcements"
giscus_category_id = "DIC_kwDOPTLco84Ctb-O"

[[params.socials]]
  name = "HomePage"
  link = "https://homepage.turingzy.cn/"
[[params.socials]]
  name = "Github"
  link = "https://github.com/chiredeqiudong-dev/"